export const goiThauData = [
  {
    id: "GT01",
    ten: "Gói thầu phần thô",
    nhaThau: [
      { id: "NT01", ten: "Công ty A", maSoThue: "MST-001", diaChi: "Hà Nội" },
      { id: "NT02", ten: "Công ty B", maSoThue: "MST-002", diaChi: "Đà Nẵng" },
      { id: "NT03", ten: "Công ty C", maSoThue: "MST-003", diaChi: "TP.HCM" },
    ],
    hangMuc: [
      {
        id: "HM01",
        ten: "Xây móng",
        ngayBatDau: "2025-05-01",
        ngayKetThuc: "2025-05-30",
        klKeHoach: 100,
        klThucHien: 100,
      },
      {
        id: "HM02",
        ten: "Đổ cột trụ",
        ngayBatDau: "2025-06-01",
        ngayKetThuc: "2025-06-20",
        klKeHoach: 80,
        klThucHien: 50,
      },
      {
        id: "HM03",
        ten: "Xây tường",
        ngayBatDau: "2025-06-21",
        ngayKetThuc: "2025-07-15",
        klKeHoach: 120,
        klThucHien: 70,
      },
    ],
  },
  {
    id: "GT02",
    ten: "Gói thầu hoàn thiện",
    nhaThau: [
      { id: "NT04", ten: "Công ty D", maSoThue: "MST-004", diaChi: "Hải Phòng" },
      { id: "NT05", ten: "Công ty E", maSoThue: "MST-005", diaChi: "Bình Dương" },
    ],
    hangMuc: [
      {
        id: "HM04",
        ten: "Lát gạch",
        ngayBatDau: "2025-07-01",
        ngayKetThuc: "2025-07-20",
        klKeHoach: 200,
        klThucHien: 180,
      },
      {
        id: "HM05",
        ten: "Sơn tường",
        ngayBatDau: "2025-07-21",
        ngayKetThuc: "2025-08-15",
        klKeHoach: 150,
        klThucHien: 100,
      },
      {
        id: "HM06",
        ten: "Lắp cửa",
        ngayBatDau: "2025-08-16",
        ngayKetThuc: "2025-08-30",
        klKeHoach: 50,
        klThucHien: 50,
      },
    ],
  },
  {
    id: "GT03",
    ten: "Gói thầu điện nước",
    nhaThau: [
      { id: "NT06", ten: "Công ty F", maSoThue: "MST-006", diaChi: "Cần Thơ" },
      { id: "NT07", ten: "Công ty G", maSoThue: "MST-007", diaChi: "Huế" },
      { id: "NT08", ten: "Công ty H", maSoThue: "MST-008", diaChi: "Hà Nam" },
    ],
    hangMuc: [
      {
        id: "HM07",
        ten: "Lắp đặt hệ thống điện",
        ngayBatDau: "2025-05-15",
        ngayKetThuc: "2025-06-05",
        klKeHoach: 90,
        klThucHien: 90,
      },
      {
        id: "HM08",
        ten: "Lắp đặt ống nước",
        ngayBatDau: "2025-06-06",
        ngayKetThuc: "2025-06-25",
        klKeHoach: 120,
        klThucHien: 110,
      },
      {
        id: "HM09",
        ten: "Kiểm tra hệ thống",
        ngayBatDau: "2025-06-26",
        ngayKetThuc: "2025-07-10",
        klKeHoach: 70,
        klThucHien: 30,
      },
    ],
  },
  {
    id: "GT04",
    ten: "Gói thầu cảnh quan",
    nhaThau: [
      { id: "NT09", ten: "Công ty I", maSoThue: "MST-009", diaChi: "Quảng Ninh" },
      { id: "NT10", ten: "Công ty J", maSoThue: "MST-010", diaChi: "Hòa Bình" },
    ],
    hangMuc: [
      {
        id: "HM10",
        ten: "Trồng cây xanh",
        ngayBatDau: "2025-06-10",
        ngayKetThuc: "2025-06-30",
        klKeHoach: 500,
        klThucHien: 480,
      },
      {
        id: "HM11",
        ten: "Lát đá sân vườn",
        ngayBatDau: "2025-07-01",
        ngayKetThuc: "2025-07-25",
        klKeHoach: 300,
        klThucHien: 250,
      },
      {
        id: "HM12",
        ten: "Lắp đặt đèn trang trí",
        ngayBatDau: "2025-07-26",
        ngayKetThuc: "2025-08-05",
        klKeHoach: 100,
        klThucHien: 100,
      },
    ],
  },
];
