export const vuongMacData = [
    {
      goiThau: "Gói thầu phần thô",
      nhaThau: "Công ty A",
      hangMuc: "Xây móng",
      noiDung: "Phát hiện lớp đất yếu cần gia cố",
      deXuat: "Gia cố bằng cọc xi măng",
      trangThaiXuLy: "Chưa xử lý",
      ngayCapNhat: "2025-07-10",
    },
    {
      goiThau: "Gói thầu phần thô",
      nhaThau: "Công ty B",
      hangMuc: "Đổ cột trụ",
      noiDung: "Thiếu thép theo thiết kế",
      deXuat: "Bổ sung thép đúng tiêu chuẩn",
      trangThaiXuLy: "Đang xử lý",
      ngayCapNhat: "2025-07-12",
    },
    {
      goiThau: "Gói thầu hoàn thiện",
      nhaThau: "Công ty C",
      hangMuc: "Lát gạch",
      noiDung: "Gạch bị nứt nhiều",
      deXuat: "Đổi lô gạch khác",
      trangThaiXuLy: "Đã xử lý",
      ngayCapNhat: "2025-07-15",
    },
    {
      goiThau: "Gói thầu hoàn thiện",
      nhaThau: "Công ty A",
      hangMuc: "Sơn tường",
      noiDung: "Sơn bong tróc",
      deXuat: "Sơn lại bằng loại sơn chống ẩm",
      trangThaiXuLy: "Đang xử lý",
      ngayCapNhat: "2025-07-16",
    },
    {
      goiThau: "Gói thầu điện nước",
      nhaThau: "Công ty D",
      hangMuc: "Lắp đặt hệ thống điện",
      noiDung: "Thiếu tủ điện chính",
      deXuat: "Mua thêm tủ điện",
      trangThaiXuLy: "Chưa xử lý",
      ngayCapNhat: "2025-07-17",
    },
    {
      goiThau: "Gói thầu điện nước",
      nhaThau: "Công ty E",
      hangMuc: "Lắp đặt ống nước",
      noiDung: "Ống nước rò rỉ",
      deXuat: "Thay thế đoạn ống hỏng",
      trangThaiXuLy: "Đã xử lý",
      ngayCapNhat: "2025-07-17",
    },
  ];
  